### ISSUE TITLE
Fix Total Profit DB error

### ISSUE THREAD

**Issue by IlluvatarEru** [IlluvatarEru/mev-inspect-py#16]
When trying to save the profits to the db I get the below error. Is there a missing command to run when launching docker and tilt to setup the DB?
```
INFO:mev_inspect.inspector:Gathered 1000 blocks to inspect
fetching from node... 34500000 34500009
fetching from node... 34500010 34500019
fetching from node... 34500020 34500029
fetching from node... 34500030 34500039
fetching from node... 34500040 34500049
fetching from node... 34500050 34500059
fetching from node... 34500060 34500069
fetching from node... 34500070 34500079
writing profits of 3 mev transactions
fetching from node... 34500080 34500089
ERROR:mev_inspect.inspector:Exited due to <class 'psycopg2.errors.UniqueViolation'>
Traceback (most recent call last):
  File "/app/mev_inspect/inspector.py", line 84, in inspect_many_blocks
    await asyncio.gather(*tasks)
  File "/app/mev_inspect/inspector.py", line 99, in safe_inspect_many_blocks
    return await inspect_many_blocks(
  File "/app/mev_inspect/inspect_block.py", line 98, in inspect_many_blocks
    write_total_profits_for_blocks(
  File "/app/mev_inspect/crud/total_profits.py", line 22, in write_total_profits_for_blocks
    write_as_csv(inspect_db_session, "total_profit_by_block", items_generator)
  File "/app/mev_inspect/db.py", line 80, in write_as_csv
    cursor.copy_from(csv_iterator, table_name, sep="|")
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "total_profit_by_block_pkey"
DETAIL:  Key (block_number)=(34500002) already exists.
CONTEXT:  COPY total_profit_by_block, line 2
```

See [this branch](https://github.com/IlluvatarEru/mev-inspect-py/pull/17/files) to reproduce the error

**Comment by IlluvatarEru** [comment]
The command: `./mev inspect-many 34500000 34501000`
Now getting:
```
fetching from node... 34500070 34500079
ERROR:mev_inspect.inspector:Exited due to <class 'sqlalchemy.exc.IntegrityError'>
Traceback (most recent call last):
  File "/home/flashbot/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1751, in _execute_context
    self.dialect.do_executemany(
  File "/home/flashbot/.local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 962, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/flashbot/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "total_profit_by_block_pkey"
DETAIL:  Key (block_number)=(34500002) already exists.

```
